# Generated by Django 3.2.6 on 2021-08-11 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210811_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='datainicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 12, 55, 55, 772204, tzinfo=utc)),
        ),
    ]
