# Generated by Django 3.2.6 on 2021-08-11 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_curso_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='datainicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 12, 59, 16, 898385, tzinfo=utc)),
        ),
    ]
